### ISSUE TITLE
Installation - Python Failed!

### ISSUE THREAD

**Issue by Fang-Kevin** [czbiohub/tabula-muris#210]
Hello~

I want to create conda environment via

"conda env create -f environment.yml" as you recommanded.

But it failed, the error message is 

"
Using Anaconda API: https://api.anaconda.org

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 79, in execute
        directory=os.getcwd())
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 84, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 72, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 53, in get_single_node
        document = self.compose_document()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 76, in compose_document
        self.get_event()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 136, in get_event
        self.current_event = self.state()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 215, in parse_document_end
        token = self.peek_token()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 239, in fetch_more_tokens
        return self.fetch_value()
      File "/Users/rorschachsilver/anaconda/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 598, in fetch_value
        self.get_mark())
    ScannerError: mapping values are not allowed here
      in "<byte string>", line 374, column 86:
         ... on-absolute mt-5" style="z-index: 99;">
                                             ^

`$ /Users/rorschachsilver/anaconda/bin/conda-env create -f environment.yml`

"

My os is macOS.

Thanks for your help

**Comment by LodeVanB** [comment]
I see python 2.7 in your report is Python 3.6 on your system? I think this is required for setting up the environment ...

**Comment by aopisco** [comment]
@Fang-Kevin are you still having that problem?

**Comment by LodeVanB** [comment]
No I had another one but solved it with a rerun of the bash script
